### ISSUE TITLE
Wrong version in composer.json

### ISSUE THREAD

**Issue by brandonkelly** [angell-co/Portal#3]
The Plugin Store isn't picking this up because there's a version mismatch between the tag name & `version` in composer.json.

https://github.com/angell-co/Portal/blob/166e2aaac40c382220c4101da2291f4c8036052d/composer.json#L5

**Comment by joshangell** [comment]
Good spot thanks, fixed in ebf7d420c4a7e33b698bd7d04488ac6f1bc2a774
