### ISSUE TITLE
Iframe size issue with craft 3.1 live preview

### ISSUE THREAD

**Issue by nettum** [angell-co/Portal#7]
There seems to be an issue with scaling the live preview iframe inside the Portal device mask when using Portal with Craft 3.1. This may be related to the way the iframe gets injected in 3.1 (see issue https://github.com/craftcms/cms/issues/3366).

Here are a few screenshots:
![image](https://user-images.githubusercontent.com/798156/52427080-8d782880-2aff-11e9-809f-d9aa85752f2c.png)

![image](https://user-images.githubusercontent.com/798156/52427127-a680d980-2aff-11e9-816c-a22948a01bd2.png)

![image](https://user-images.githubusercontent.com/798156/52427145-ae407e00-2aff-11e9-8dc2-c3338c89880a.png)

Tested with Craft 3.1.8 and Portal 1.0.6.

**Comment by joshangell** [comment]
@nettum this should be fixed now!

**Comment by nettum** [comment]
Awesome, thanks! Will update later today!
