### ISSUE TITLE
Not working with Commerce

### ISSUE THREAD

**Issue by samuelbirch** [angell-co/Portal#8]
If you try and add a new product, Portal throws an error saying "invalid site handle: new"

/src/Portal.php line 223

**Comment by joshangell** [comment]
Ah thanks @samuelbirch - I’ll have a look soon, should be a quick one

**Comment by samuelbirch** [comment]
Got the same issue when trying to edit a product :(

**Comment by joshangell** [comment]
Huh, sorry about that. I'll take a look later this week when I'm back at my desk!
