### ISSUE TITLE
Device previews not working

### ISSUE THREAD

**Issue by richardellisjr** [angell-co/Portal#9]
After upgrading to Craft 3.3.15 we no longer have the ability to preview devices.  On the preview page(s) we get a drop down for "Primary entry page" and "Social media preview" but no device choices.

We are running Portal 1.1.3.

Any help that can be provided would be appreciated

**Comment by nettum** [comment]
Got the same behavior here. 

Just did the following update process locally for a site:  
Round 1:
- craft 3.1.22 => 3.1.34.3

Round 2:
- craft 3.1.34.3 => 3.3.20.1

**Comment by wesleygooch** [comment]
Device previews are also not work for me. Clean install on the lastest Craft. Everything else works. no errors being logged. no console errors. I followed your install instructions. Please advise and thanks in advance.

**Comment by nettum** [comment]
Hi @joshangell,

I see this plugin has not been updated for a while. Is it abandoned or do you have any plans to update the plugin to support Craft CMS >3.5 in the future?

Just wondering if we should continue with this plugin or not when going forward with craft updates.  
If this plugin is not actively maintained anymore, would PRs be accepted/merged?

**Comment by joshangell** [comment]
This is because of the new Preview Targets feature that landed in 3.4 at some point, I think there is something in the works though in core craft that will remove the need for this plugin, but I’m unsure when it’ll land. Should no more in the new year.

**Comment by joshangell** [comment]
And it's here! PR is merged [here](https://github.com/craftcms/cms/pull/7375).

Once this lands Portal will be discontinued, I'll post a full update in due course but if anyone wants a refund just email me: josh@angell.io
